# Generated by Django 3.2.7 on 2022-01-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'superadmin'), ('2', 'schooladmin')], default='1', max_length=10),
        ),
    ]
