# Generated by Django 5.0.6 on 2024-06-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('limit', models.IntegerField()),
                ('device', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='devices/')),
            ],
        ),
    ]
