# Generated by Django 5.0.6 on 2024-06-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_merge_0002_alter_customuser_user_type_0003_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'superadmin'), ('2', 'schooladmin'), ('3', 'staff')], default='1', max_length=10),
        ),
    ]
