# Generated by Django 5.0.6 on 2024-07-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_occasion_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='occasion',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
