# Generated by Django 5.0.6 on 2024-07-28 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0012_payslip_created_at_payslip_updated_at'),
        ('management', '0010_occasion_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavereport',
            name='date',
        ),
        migrations.RemoveField(
            model_name='leavereport',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='leavereport',
            name='name',
        ),
        migrations.RemoveField(
            model_name='leavereport',
            name='number',
        ),
        migrations.AddField(
            model_name='leavereport',
            name='gap_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavereport',
            name='gap_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavereport',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='handle.member'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leavereport',
            name='reason',
            field=models.TextField(),
        ),
    ]
