# Generated by Django 3.2.7 on 2025-06-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_leavereport_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='auto_checkin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='location_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='qr_based',
            field=models.BooleanField(default=False),
        ),
    ]
