# Generated by Django 3.2.7 on 2025-06-11 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0013_alter_member_card'),
        ('management', '0014_auto_20250601_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_qrcode', to='management.organization')),
            ],
        ),
        migrations.CreateModel(
            name='LocationBased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.FloatField()),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_location', to='management.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AutoCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('checkin_time', models.TimeField()),
                ('checkout_time', models.TimeField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_auto_checkin', to='handle.member')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_auto_checkin', to='management.organization')),
            ],
        ),
    ]
