# Generated by Django 3.2.7 on 2025-06-11 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_autocheckin_locationbased_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocheckin',
            name='auto_checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_auto_checkin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='autocheckin',
            name='checkin_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='autocheckin',
            name='checkout_time',
            field=models.DateTimeField(),
        ),
    ]
