# Generated by Django 3.2.7 on 2026-04-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_auto_20250611_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='free_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='nepali_date',
            field=models.BooleanField(default=False),
        ),
    ]
