# Generated by Django 5.2.13 on 2026-05-25 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_auto_20260405_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.CharField(choices=[('school', 'School'), ('college', 'College'), ('bachelor', 'Bachelor'), ('institute', 'Institute/Consultancy'), ('office', 'Office'), ('others', 'Others')], default='others', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='course_based_attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='manual_attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='rfid_based',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Sick Leave, Maternity Leave', max_length=150)),
                ('annual_allocation', models.PositiveIntegerField(default=12, help_text='Days allowed per year')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.organization')),
            ],
        ),
        migrations.AddField(
            model_name='leavereport',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.leavetype'),
        ),
        migrations.CreateModel(
            name='WifiBased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bssid', models.CharField(help_text='WiFi BSSID/MAC address', max_length=100)),
                ('ssid', models.CharField(help_text='WiFi network name', max_length=200)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_wifi', to='management.organization')),
            ],
        ),
    ]
