# Generated by Django 5.2.13 on 2026-06-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_organization_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='feature_billing',
            field=models.BooleanField(default=False, verbose_name='Billing (Student Invoices)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='feature_branches',
            field=models.BooleanField(default=False, verbose_name='Branch Management'),
        ),
        migrations.AddField(
            model_name='organization',
            name='feature_complaints',
            field=models.BooleanField(default=False, verbose_name='Complaints'),
        ),
        migrations.AddField(
            model_name='organization',
            name='feature_events',
            field=models.BooleanField(default=False, verbose_name='Events'),
        ),
        migrations.AddField(
            model_name='organization',
            name='feature_finance',
            field=models.BooleanField(default=False, verbose_name='Finance (Income / Expense)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='feature_hrms',
            field=models.BooleanField(default=False, verbose_name='HR Module (Resignation / Documents)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='feature_leave',
            field=models.BooleanField(default=False, verbose_name='Leave Management'),
        ),
        migrations.AddField(
            model_name='organization',
            name='feature_payroll',
            field=models.BooleanField(default=False, verbose_name='Payroll & Payslips'),
        ),
        migrations.AddField(
            model_name='organization',
            name='feature_results',
            field=models.BooleanField(default=False, verbose_name='Results & Exams'),
        ),
        migrations.AddField(
            model_name='organization',
            name='feature_stock',
            field=models.BooleanField(default=False, verbose_name='Stock Management'),
        ),
        migrations.AddField(
            model_name='organization',
            name='feature_tasks',
            field=models.BooleanField(default=False, verbose_name='Task Management'),
        ),
    ]
