# Generated by Django 5.2.13 on 2026-06-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_blogpost_appointmenttype_appointment_customform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='is_paid',
            field=models.BooleanField(default=True, help_text='If unchecked, approved leave of this type will be unpaid (deducted from salary).'),
        ),
    ]
