# Generated by Django 5.2.13 on 2026-06-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_leavetype_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='feature_bulk_export',
            field=models.BooleanField(default=False, verbose_name='Bulk Data Export'),
        ),
        migrations.AddField(
            model_name='organization',
            name='feature_courses',
            field=models.BooleanField(default=False, verbose_name='Course Management'),
        ),
        migrations.AddField(
            model_name='organization',
            name='feature_member_mgmt',
            field=models.BooleanField(default=True, verbose_name='Member / Staff Management'),
        ),
        migrations.AddField(
            model_name='organization',
            name='feature_notifications',
            field=models.BooleanField(default=False, verbose_name='Notifications / SMS Alerts'),
        ),
        migrations.AddField(
            model_name='organization',
            name='feature_student_mgmt',
            field=models.BooleanField(default=False, verbose_name='Student Management'),
        ),
        migrations.AddField(
            model_name='organization',
            name='feature_study_gap',
            field=models.BooleanField(default=False, verbose_name='Study Gap / Teaching Log'),
        ),
    ]
