# Generated by Django 5.2.13 on 2026-07-01 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_organization_feature_bulk_export_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='created_by_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('trial', 'Trial'), ('expired', 'Expired')], default='trial', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partial', 'Partial'), ('trial', 'Trial'), ('expired', 'Expired')], default='trial', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_plan',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'superadmin'), ('2', 'schooladmin'), ('3', 'staff'), ('4', 'agent')], default='1', max_length=10),
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='agents/')),
                ('company_name', models.CharField(blank=True, max_length=300)),
                ('pan_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('commission_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], default='percent', max_length=10)),
                ('commission_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('allowed_to_create_org', models.BooleanField(default=True)),
                ('allowed_to_manage_billing', models.BooleanField(default=False)),
                ('allowed_to_manage_features', models.BooleanField(default=False)),
                ('allowed_to_view_reports', models.BooleanField(default=True)),
                ('max_organizations_allowed', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_type', models.CharField(blank=True, max_length=10)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partial', 'Partial')], default='unpaid', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='management.organization')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='management.agentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AgentActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_activity_logs', to='management.organization')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='management.agentprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='management.agentprofile'),
        ),
    ]
