# Generated by Django 5.2.13 on 2026-07-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_organization_created_by_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='enable_qr_attendance',
            field=models.BooleanField(default=False, verbose_name='Dynamic QR Attendance'),
        ),
    ]
