# Generated by Django 5.2.16 on 2026-07-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_organization_feature_timesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='feature_id_cards',
            field=models.BooleanField(default=False, verbose_name='ID Card Generation'),
        ),
    ]
