# Generated by Django 4.2.5 on 2026-07-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_organization_feature_id_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='feature_clients',
            field=models.BooleanField(default=False, verbose_name='Client Follow-Up (CRM)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='feature_field_visits',
            field=models.BooleanField(default=False, verbose_name='Field Visit / Location Sharing'),
        ),
    ]
