# Generated by Django 4.2.5 on 2026-07-18 14:06

from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_organization_feature_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='allowed_features',
            field=models.JSONField(blank=True, default=management.models.default_allowed_features, help_text="Feature keys this org's plan is allowed to use. Superadmin-controlled; schooladmin can only toggle features within this list."),
        ),
    ]
