# Generated by Django 4.2.5 on 2026-07-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_organization_allowed_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Shown in search results and social previews. Falls back to excerpt if blank.', max_length=300),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords.', max_length=300),
        ),
    ]
