# Generated by Django 4.2.5 on 2026-07-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_blogpost_meta_description_blogpost_meta_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='feature_face_attendance',
            field=models.BooleanField(default=False, verbose_name='Face Attendance'),
        ),
    ]
