# Generated by Django 5.2.16 on 2026-07-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_organization_feature_face_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='feature_notices',
            field=models.BooleanField(default=False, verbose_name='Notice Board / Announcements'),
        ),
    ]
