# Generated by Django 4.2.5 on 2026-07-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_featureprice_organization_commercial_fields'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='occasion',
            constraint=models.UniqueConstraint(fields=('org', 'name', 'date'), name='unique_occasion_name_date_per_org'),
        ),
    ]
