# Generated by Django 5.2.16 on 2026-07-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0035_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('member_limit', models.PositiveIntegerField()),
                ('selected_feature_keys', models.JSONField(blank=True, default=list)),
                ('package_name', models.CharField(blank=True, default='', max_length=200)),
                ('base_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('feature_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ('-created_at', '-id')},
        ),
        migrations.AddField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
