# Generated by Django 5.2.16 on 2026-08-06 16:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0037_seed_homepage_faqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_shift_end_time',
            field=models.TimeField(default=datetime.time(17, 0), help_text='Company-wide default check-out time for new members.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_shift_start_time',
            field=models.TimeField(default=datetime.time(9, 0), help_text='Company-wide default check-in time for new members.'),
        ),
        migrations.CreateModel(
            name='OrganizationShiftOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_overrides', to='management.organization')),
            ],
            options={
                'ordering': ('-date',),
                'constraints': [models.UniqueConstraint(fields=('org', 'date'), name='unique_org_shift_override_per_date')],
            },
        ),
    ]
