# Generated by Django 5.2.16 on 2026-08-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0038_organization_default_shift_and_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, help_text="Organization's contact email, shown on the profile page and used as a reply-to for org-wide notices.", max_length=254, null=True),
        ),
    ]
