# Generated by Django 3.2.7 on 2022-01-02 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=30)),
                ('port_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('privilege', models.IntegerField(default=1)),
                ('group', models.CharField(blank=True, choices=[('Teacher', 'Teacher'), ('Student', 'Student'), ('Staff', 'Staff')], max_length=200, null=True)),
                ('card', models.CharField(max_length=14, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200)),
                ('address', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone', models.BigIntegerField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('black_list', models.BooleanField(default=False)),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_type', to='handle.classification')),
            ],
        ),
    ]
