# Generated by Django 3.2.7 on 2022-01-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='group',
        ),
        migrations.AlterField(
            model_name='member',
            name='card',
            field=models.CharField(max_length=14),
        ),
    ]
