# Generated by Django 3.2.7 on 2022-01-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0003_auto_20220102_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='salary_per_hour',
            field=models.IntegerField(default=15),
        ),
    ]
