# Generated by Django 5.0.6 on 2024-06-23 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0004_member_salary_per_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('month', models.CharField(max_length=200)),
                ('salary', models.DecimalField(decimal_places=3, max_digits=30)),
                ('tax', models.DecimalField(decimal_places=3, max_digits=30)),
                ('total', models.DecimalField(decimal_places=3, max_digits=30)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_pay_slip', to='handle.member')),
            ],
        ),
    ]
