# Generated by Django 5.0.6 on 2024-07-15 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0009_staff_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_member', to='handle.member'),
        ),
    ]
