# Generated by Django 5.0.6 on 2024-07-18 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0011_alter_attendancerecord_mem'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
