# Generated by Django 5.0.6 on 2024-06-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_customuser_user_type'),
        ('management', '0003_pricing'),
    ]

    operations = [
    ]
