# Generated by Django 5.0.6 on 2024-06-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_organization_address_organization_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='member_limit',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='organization',
            name='mutifeature_enable',
            field=models.BooleanField(default=False),
        ),
    ]
