# Generated by Django 5.0.6 on 2024-06-24 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_organization_member_limit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
