# Generated by Django 5.0.6 on 2024-07-18 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_delete_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.CharField(max_length=300)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_holiday', to='management.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_occasion', to='management.organization')),
            ],
        ),
    ]
