# Generated by Django 5.0.6 on 2024-07-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_holiday_occasion'),
    ]

    operations = [
        migrations.AddField(
            model_name='occasion',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
