# Generated by Django 5.0.6 on 2024-07-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_remove_leavereport_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereport',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavereport',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
