# Generated by Django 5.0.6 on 2024-07-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_leavereport_approved_leavereport_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereport',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
