# Generated by Django 3.2.7 on 2022-01-02 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('handle', '0001_initial'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.organization'),
        ),
        migrations.AddField(
            model_name='device',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.organization'),
        ),
        migrations.AddField(
            model_name='classification',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.organization'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='mem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_record', to='handle.member'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.organization'),
        ),
    ]
