# Generated by Django 5.0.6 on 2024-07-14 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0006_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendingClassification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_classificaton', to='handle.classification')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attending', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
