# Generated by Django 5.0.6 on 2024-07-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0007_attendingclassification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='member',
        ),
    ]
