# Generated by Django 5.0.6 on 2024-07-16 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0010_alter_staff_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='mem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_record', to='handle.member'),
        ),
    ]
