# Generated by Django 3.2.7 on 2025-06-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0012_payslip_created_at_payslip_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='card',
            field=models.CharField(default='00000000000000', max_length=14),
        ),
    ]
