# Generated by Django 3.2.7 on 2025-06-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0013_alter_member_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='card',
            field=models.CharField(blank=True, default='00000000000000', max_length=14, null=True),
        ),
    ]
