# Generated by Django 3.2.7 on 2025-06-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0015_alter_member_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='scanned_time_np',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
