# Generated by Django 5.2.13 on 2026-05-25 08:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0016_attendancerecord_scanned_time_np'),
        ('management', '0018_organization_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='month',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='total',
        ),
        migrations.AddField(
            model_name='member',
            name='make_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='salary_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='member',
            name='salary_type',
            field=models.CharField(choices=[('hourly', 'Per Hour'), ('daily', 'Per Day'), ('weekly', 'Per Week'), ('monthly', 'Per Month')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='shift_end_time',
            field=models.TimeField(default=datetime.time(17, 0), help_text='Expected check-out time (e.g., 05:00 PM)'),
        ),
        migrations.AddField(
            model_name='member',
            name='shift_start_time',
            field=models.TimeField(default=datetime.time(9, 0), help_text='Expected check-in time (e.g., 09:00 AM)'),
        ),
        migrations.AddField(
            model_name='member',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='e.g. 1.00 for 1% TDS', max_digits=5),
        ),
        migrations.AddField(
            model_name='payslip',
            name='generated_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='holidays',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='month_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='net_payable',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='org',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='management.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='paid_leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='present_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='salary_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='tax_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='unpaid_absences',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handle.member'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partial', 'Partial'), ('Paid', 'Paid')], default='Unpaid', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_bills', to='handle.member')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_bills', to='management.organization')),
            ],
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='handle.bill')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_course', to='management.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CourseAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_classification', to='handle.classification')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_attendance', to='handle.course')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_course_attendance', to='management.organization')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='staff_course_attendance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_exams', to='management.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('full_marks', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('pass_marks', models.DecimalField(decimal_places=2, default=40, max_digits=5)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='handle.classification')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_subjects', to='management.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ResultRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to='handle.examterm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='handle.member')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_records', to='handle.subject')),
            ],
            options={
                'unique_together': {('student', 'exam', 'subject')},
            },
        ),
    ]
