# Generated by Django 5.2.13 on 2026-06-23 02:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0019_member_date_of_birth_stockcategory_stockitem_and_more'),
        ('management', '0018_organization_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pf_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='probation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='probation_leave_cut_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='probation_review_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('passed', 'Passed'), ('extended', 'Extended'), ('failed', 'Failed')], default='not_required', max_length=30),
        ),
        migrations.AddField(
            model_name='member',
            name='probation_salary_percentage',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='member',
            name='probation_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='ssf_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='staff_type',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary'), ('intern', 'Intern'), ('contract', 'Contract'), ('probation', 'Probation')], default='permanent', max_length=30),
        ),
        migrations.AddField(
            model_name='payslip',
            name='advance_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='allowance_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='bonus_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='loan_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='other_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='pf_employee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='pf_employer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='probation_adjustment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='ssf_employee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='ssf_employer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('allowance', 'Allowance'), ('bonus', 'Bonus'), ('deduction', 'Other Deduction'), ('advance', 'Advance Salary'), ('loan', 'Loan Deduction')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_adjustments', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_adjustments', to='handle.member')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_adjustments', to='management.organization')),
            ],
            options={
                'ordering': ('-effective_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PayrollPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_employee_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('pf_employer_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('ssf_employee_percentage', models.DecimalField(decimal_places=2, default=11.0, max_digits=5)),
                ('ssf_employer_percentage', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('probation_salary_percentage', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('probation_leave_cut_enabled', models.BooleanField(default=True)),
                ('probation_reminder_days', models.PositiveIntegerField(default=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_policy', to='management.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ProbationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('extended', 'Extended'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probation_reviews', to='handle.member')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probation_reviews', to='management.organization')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probation_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-review_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProvidentFundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=100)),
                ('employee_contribution', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('employer_contribution', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('recorded_on', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf_records', to='handle.member')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf_records', to='management.organization')),
                ('payslip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pf_records', to='handle.payslip')),
            ],
            options={
                'ordering': ('-recorded_on',),
            },
        ),
        migrations.CreateModel(
            name='SocialSecurityFundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=100)),
                ('employee_contribution', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('employer_contribution', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('recorded_on', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssf_records', to='handle.member')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssf_records', to='management.organization')),
                ('payslip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssf_records', to='handle.payslip')),
            ],
            options={
                'ordering': ('-recorded_on',),
            },
        ),
    ]
