# Generated by Django 5.2.13 on 2026-06-29 15:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0023_task_management'),
        ('management', '0021_leavetype_is_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payslip',
            options={'ordering': ('-from_date', '-id')},
        ),
        migrations.AddField(
            model_name='payslip',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_payslips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payslip',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('paid', 'Paid')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='AdvanceSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('num_installments', models.PositiveIntegerField(default=1, help_text='Number of months to recover over')),
                ('installment_amount', models.DecimalField(decimal_places=2, help_text='Auto-deducted each payslip cycle', max_digits=12)),
                ('paid_installments', models.PositiveIntegerField(default=0)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('effective_date', models.DateField(default=django.utils.timezone.localdate, help_text='Recovery starts from this date')),
                ('status', models.CharField(choices=[('active', 'Active — recovering'), ('fully_recovered', 'Fully Recovered'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_advances', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_salaries', to='handle.member')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_salaries', to='management.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
