# Generated by Django 5.2.13 on 2026-06-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0024_payslip_status_advance_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignationrecord',
            name='self_applied',
            field=models.BooleanField(default=False),
        ),
    ]
