# Generated by Django 5.2.13 on 2026-06-30 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0027_student_billing_fields_and_sendlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_items', to='handle.subject'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('passed_out', 'Passed Out'), ('dropped', 'Dropped'), ('transferred', 'Transferred'), ('suspended', 'Suspended'), ('restricted', 'Restricted'), ('resigned', 'Resigned'), ('intern', 'Intern'), ('probation', 'Probation')], default='active', max_length=30),
        ),
    ]
