# Generated by Django 5.2.13 on 2026-06-30 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0028_billitem_subject_alter_member_status'),
        ('management', '0022_organization_feature_bulk_export_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_attendance', models.BooleanField(default=True)),
                ('can_add_attendance', models.BooleanField(default=False)),
                ('can_edit_attendance', models.BooleanField(default=False)),
                ('can_export_attendance', models.BooleanField(default=False)),
                ('can_view_members', models.BooleanField(default=False)),
                ('can_add_members', models.BooleanField(default=False)),
                ('can_edit_members', models.BooleanField(default=False)),
                ('can_delete_members', models.BooleanField(default=False)),
                ('can_view_payroll', models.BooleanField(default=False)),
                ('can_generate_payroll', models.BooleanField(default=False)),
                ('can_view_own_payslip', models.BooleanField(default=True)),
                ('can_manage_payroll_cfg', models.BooleanField(default=False)),
                ('can_view_leave', models.BooleanField(default=True)),
                ('can_request_leave', models.BooleanField(default=True)),
                ('can_approve_leave', models.BooleanField(default=False)),
                ('can_view_leave_report', models.BooleanField(default=False)),
                ('can_view_stock', models.BooleanField(default=False)),
                ('can_add_stock', models.BooleanField(default=False)),
                ('can_edit_stock', models.BooleanField(default=False)),
                ('can_delete_stock', models.BooleanField(default=False)),
                ('can_stock_in_out', models.BooleanField(default=False)),
                ('can_view_tasks', models.BooleanField(default=True)),
                ('can_assign_tasks', models.BooleanField(default=False)),
                ('can_manage_tasks', models.BooleanField(default=False)),
                ('can_view_task_report', models.BooleanField(default=False)),
                ('can_view_courses', models.BooleanField(default=False)),
                ('can_manage_courses', models.BooleanField(default=False)),
                ('can_publish_results', models.BooleanField(default=False)),
                ('can_view_result_report', models.BooleanField(default=False)),
                ('can_view_billing', models.BooleanField(default=False)),
                ('can_generate_bills', models.BooleanField(default=False)),
                ('can_record_payment', models.BooleanField(default=False)),
                ('can_view_dues', models.BooleanField(default=False)),
                ('can_export_billing', models.BooleanField(default=False)),
                ('can_view_finance', models.BooleanField(default=False)),
                ('can_manage_finance', models.BooleanField(default=False)),
                ('can_view_events', models.BooleanField(default=True)),
                ('can_manage_events', models.BooleanField(default=False)),
                ('can_view_complaints', models.BooleanField(default=True)),
                ('can_manage_complaints', models.BooleanField(default=False)),
                ('can_view_hrms', models.BooleanField(default=False)),
                ('can_manage_hrms', models.BooleanField(default=False)),
                ('can_view_branches', models.BooleanField(default=False)),
                ('can_manage_branches', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_export_reports', models.BooleanField(default=False)),
                ('can_bulk_export', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_permission', to='handle.member')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_permissions', to='management.organization')),
            ],
            options={
                'verbose_name': 'Staff Permission',
                'verbose_name_plural': 'Staff Permissions',
            },
        ),
    ]
