# Generated by Django 5.2.13 on 2026-07-01 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0029_staffpermission'),
        ('management', '0024_organization_enable_qr_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='attendance_method',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('biometric', 'Biometric/RFID'), ('gps', 'GPS'), ('wifi', 'WiFi'), ('qr', 'QR Attendance'), ('auto', 'Auto Checkin')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='staffpermission',
            name='can_scan_qr_attendance',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='QRAttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('closed', 'Closed')], default='active', max_length=10)),
                ('valid_from', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('total_scans', models.PositiveIntegerField(default=0)),
                ('successful_scans', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_attendance_sessions', to='handle.branch')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_qr_sessions', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_attendance_sessions', to='management.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='QRAttendanceScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('expired', 'Expired'), ('duplicate', 'Duplicate'), ('invalid_org', 'Invalid Org'), ('inactive_member', 'Inactive Member'), ('session_closed', 'Session Closed'), ('error', 'Error')], default='success', max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=300)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('attendance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='handle.attendancerecord')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_scan_logs', to='handle.member')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.organization')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='handle.qrattendancesession')),
            ],
            options={
                'ordering': ('-scanned_at',),
            },
        ),
    ]
