# Generated by Django 5.2.16 on 2026-07-12 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0031_timesheet_timesheetentry_staffpermission_timesheet'),
        ('management', '0025_organization_feature_timesheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('member', 'org', 'from_date', 'to_date'), name='unique_payslip_per_member_period'),
        ),
    ]
