# Generated by Django 5.2.16 on 2026-07-12 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0032_payslip_unique_payslip_per_member_period'),
        ('management', '0026_organization_feature_id_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, help_text='Used on ID cards and profile.', null=True, upload_to='member_photos'),
        ),
        migrations.AddField(
            model_name='member',
            name='roll_number',
            field=models.CharField(blank=True, help_text='Roll / registration number, shown on ID cards.', max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='IDCardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_size', models.CharField(choices=[('cr80', 'Standard CR80 (85.6mm x 54mm / 3.375in x 2.125in)'), ('custom', 'Custom size')], default='cr80', max_length=10)),
                ('custom_width_mm', models.PositiveIntegerField(default=86, help_text='Only used when card size is Custom.')),
                ('custom_height_mm', models.PositiveIntegerField(default=54, help_text='Only used when card size is Custom.')),
                ('photo_size', models.CharField(choices=[('small', 'Small (20mm x 20mm)'), ('medium', 'Medium (25mm x 25mm)'), ('large', 'Large (30mm x 30mm)'), ('custom', 'Custom size')], default='medium', max_length=10)),
                ('custom_photo_size_mm', models.PositiveIntegerField(default=25, help_text='Only used when photo size is Custom.')),
                ('front_background', models.ImageField(blank=True, null=True, upload_to='id_card_backgrounds')),
                ('back_background', models.ImageField(blank=True, null=True, upload_to='id_card_backgrounds')),
                ('show_logo', models.BooleanField(default=True)),
                ('show_org_name', models.BooleanField(default=True)),
                ('show_photo', models.BooleanField(default=True)),
                ('show_member_id', models.BooleanField(default=True)),
                ('show_roll_number', models.BooleanField(default=True)),
                ('show_address', models.BooleanField(default=True)),
                ('show_phone', models.BooleanField(default=True)),
                ('show_email', models.BooleanField(default=True)),
                ('show_classification', models.BooleanField(default=True, verbose_name='Show classification / department')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_card_template', to='management.organization')),
            ],
        ),
    ]
