# Generated by Django 4.2.5 on 2026-07-18 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0027_organization_feature_clients_and_more'),
        ('handle', '0033_member_photo_member_roll_number_idcardtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_number', models.CharField(max_length=50)),
                ('client_org_name', models.CharField(max_length=300)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='management.organization')),
            ],
            options={
                'ordering': ('client_org_name',),
            },
        ),
        migrations.CreateModel(
            name='FieldVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy_meters', models.FloatField(blank=True, null=True)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_field_visits', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_visits', to='handle.member')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_visits', to='management.organization')),
            ],
            options={
                'ordering': ('-visited_at',),
            },
        ),
        migrations.AddField(
            model_name='staffpermission',
            name='can_manage_clients',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffpermission',
            name='can_send_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffpermission',
            name='can_view_clients',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffpermission',
            name='can_view_field_visits',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FieldVisitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='field_visit_reports/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='handle.fieldvisit')),
            ],
        ),
        migrations.CreateModel(
            name='ClientFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('follow_up_date', models.DateField()),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='handle.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_follow_ups', to='management.organization')),
                ('visited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_follow_ups', to='handle.member')),
            ],
            options={
                'ordering': ('-follow_up_date', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('org', 'client_number'), name='unique_client_number_per_org'),
        ),
    ]
