# Generated by Django 4.2.5 on 2026-07-18 05:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0034_client_fieldvisit_staffpermission_can_manage_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='overtime_rate_multiplier_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Per-member overtime multiplier override (e.g. 1.50 = 1.5x). Leave blank to use the org default.', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='overtime_rate_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Default overtime pay multiplier (e.g. 1.50 = 1.5x normal hourly rate)', max_digits=4),
        ),
        migrations.AddField(
            model_name='payslip',
            name='overtime_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8),
        ),
    ]
