# Generated by Django 4.2.5 on 2026-07-18 07:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0035_member_overtime_rate_multiplier_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='overtime_rate_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5),
        ),
    ]
