# Generated by Django 4.2.5 on 2026-07-18 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0036_payslip_overtime_rate_multiplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheet',
            options={'ordering': ('-date', '-id')},
        ),
        migrations.AlterModelOptions(
            name='timesheetentry',
            options={'ordering': ('task',)},
        ),
        migrations.AlterUniqueTogether(
            name='timesheetentry',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='period_start',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=datetime.date(2026, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.UniqueConstraint(fields=('member', 'org', 'date'), name='uniq_timesheet_member_org_date'),
        ),
        migrations.RemoveField(
            model_name='timesheetentry',
            name='date',
        ),
    ]
