# Generated by Django 4.2.5 on 2026-07-18 15:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0037_alter_timesheet_options_alter_timesheetentry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceInstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='handle.advancesalary')),
                ('payslip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_payments', to='handle.payslip')),
            ],
            options={
                'ordering': ('-paid_on', '-id'),
            },
        ),
    ]
