# Generated by Django 4.2.5 on 2026-07-19 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0038_advanceinstallmentpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldvisit',
            name='area_name',
            field=models.CharField(blank=True, help_text='Reverse-geocoded address / area name of the shared location.', max_length=300),
        ),
        migrations.AddField(
            model_name='fieldvisit',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Optional client visited on this trip.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_visits', to='handle.client'),
        ),
    ]
