# Generated by Django 4.2.5 on 2026-07-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0039_fieldvisit_area_name_fieldvisit_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollpolicy',
            name='late_grace_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Grace period for late check-in (minutes). Lateness within this window is not deducted from salary.'),
        ),
    ]
