# Generated by Django 4.2.5 on 2026-07-19 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_blogpost_meta_description_blogpost_meta_keywords'),
        ('handle', '0040_payrollpolicy_late_grace_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='management.organization')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ShiftWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='handle.shift')),
            ],
            options={
                'ordering': ('order', 'start_time'),
            },
        ),
        migrations.AddField(
            model_name='member',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Optional multi-window shift. Overrides the single check-in/check-out times above.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='handle.shift'),
        ),
    ]
