# Generated by Django 4.2.5 on 2026-07-19 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_blogpost_meta_description_blogpost_meta_keywords'),
        ('handle', '0041_shift_shiftwindow_member_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='attendance_method',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('biometric', 'Biometric/RFID'), ('gps', 'GPS'), ('wifi', 'WiFi'), ('qr', 'QR Attendance'), ('facial', 'Facial Recognition'), ('auto', 'Auto Checkin')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='MemberFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptors', models.JSONField(default=list, help_text='List of 128-float face descriptors (one per enrolled sample).')),
                ('sample_image', models.ImageField(blank=True, null=True, upload_to='member_faces/')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_profile', to='handle.member')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_faces', to='management.organization')),
            ],
        ),
    ]
