# Generated by Django 4.2.5 on 2026-07-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0042_alter_attendancerecord_attendance_method_memberface'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='shift',
        ),
        migrations.AddField(
            model_name='member',
            name='shifts',
            field=models.ManyToManyField(blank=True, help_text="One or more shifts. Their windows combine to form the member's daily schedule (supports split / multiple shifts).", related_name='members', to='handle.shift'),
        ),
    ]
