# Generated by Django 4.2.5 on 2026-07-19 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_blogpost_meta_description_blogpost_meta_keywords'),
        ('handle', '0043_remove_member_shift_member_shifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='live_tracking_enabled',
            field=models.BooleanField(default=False, help_text='Allow live GPS trail tracking for this member (field staff / marketers).'),
        ),
        migrations.CreateModel(
            name='LocationPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy_meters', models.FloatField(blank=True, null=True)),
                ('tracked_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='handle.member')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='management.organization')),
            ],
            options={
                'ordering': ('tracked_at',),
                'indexes': [models.Index(fields=['member', 'tracked_at'], name='handle_loca_member__69b305_idx')],
            },
        ),
    ]
