# Generated by Django 4.2.5 on 2026-07-19 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0044_member_live_tracking_enabled_locationping'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfollowup',
            name='field_visit',
            field=models.ForeignKey(blank=True, help_text='The field visit (GPS location) this follow-up was logged from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='handle.fieldvisit'),
        ),
    ]
