# Generated by Django 4.2.5 on 2026-07-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0046_client_crm_fields_customer_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbill',
            name='bill_image',
            field=models.ImageField(blank=True, null=True, upload_to='bill_images/'),
        ),
    ]
