# Generated by Django 4.2.5 on 2026-07-24 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('handle', '0047_customerbill_vat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='field_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='handle.fieldvisit'),
        ),
        migrations.AddField(
            model_name='fieldvisit',
            name='review_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='fieldvisit',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldvisit',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_field_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldvisit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='attendance_method',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('biometric', 'Biometric/RFID'), ('gps', 'GPS'), ('wifi', 'WiFi'), ('qr', 'QR Attendance'), ('facial', 'Facial Recognition'), ('auto', 'Auto Checkin'), ('field_visit', 'Field Visit Approval')], default='', max_length=20),
        ),
    ]
