# Generated by Django 5.2.16 on 2026-07-24 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0048_attendancerecord_field_visit_fieldvisit_review_note_and_more'),
        ('management', '0030_organization_feature_face_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, default='fa-puzzle-piece', max_length=50)),
                ('category', models.SlugField(blank=True, help_text="Matches a PERMISSION_REGISTRY category slug, or left blank for 'Custom'.")),
                ('description', models.CharField(blank=True, max_length=255)),
                ('requires', models.JSONField(blank=True, default=list, help_text='Other feature keys (legacy or dynamic) this depends on.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dynamic Feature',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='DynamicPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, default='fa-check-circle', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='handle.dynamicfeature')),
            ],
            options={
                'verbose_name': 'Dynamic Permission',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationFeatureGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_grants', to='handle.dynamicfeature')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_features', to='management.organization')),
            ],
            options={
                'verbose_name': 'Organization Feature Grant',
                'unique_together': {('org', 'feature')},
            },
        ),
        migrations.CreateModel(
            name='StaffPermissionGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_perm_grants', to='handle.member')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_grants', to='handle.dynamicpermission')),
            ],
            options={
                'verbose_name': 'Staff Permission Grant',
                'unique_together': {('member', 'permission')},
            },
        ),
    ]
