# Generated by Django 5.2.16 on 2026-07-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0049_dynamicfeature_dynamicpermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
