# Generated by Django 5.2.16 on 2026-07-25 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0050_payslip_payment_date'),
        ('management', '0030_organization_feature_face_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idcardtemplate',
            options={'verbose_name': 'ID Card Template'},
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Pre-selected design on the Generate ID Cards page.'),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='name',
            field=models.CharField(choices=[('modern_corporate_vertical', 'Modern Corporate (Vertical)'), ('minimal_clean_vertical', 'Minimal Clean (Vertical)'), ('school_style_vertical', 'School Style (Vertical)'), ('corporate_landscape', 'Corporate Landscape (Horizontal)'), ('employee_professional_landscape', 'Employee Professional (Horizontal)'), ('student_landscape', 'Student Landscape (Horizontal)')], default='modern_corporate_vertical', max_length=40),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='orientation',
            field=models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal')], default='vertical', max_length=10),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='primary_color',
            field=models.CharField(default='#1e293b', help_text='Hex color, e.g. #1e293b', max_length=7),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='secondary_color',
            field=models.CharField(default='#6366f1', help_text='Hex color, e.g. #6366f1', max_length=7),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='show_barcode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='show_blood_group',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='show_designation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='show_qr_code',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='show_signature',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='show_valid_until',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='designation',
            field=models.CharField(blank=True, help_text='Job title / role, shown on ID cards.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='id_card_valid_until',
            field=models.DateField(blank=True, help_text='ID card expiry date.', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='signature',
            field=models.ImageField(blank=True, help_text='Signature image, shown on ID cards.', null=True, upload_to='member_signatures'),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_card_templates', to='management.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='idcardtemplate',
            unique_together={('org', 'name')},
        ),
    ]
