# Generated by Django 5.2.16 on 2026-07-25 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0051_alter_idcardtemplate_options_and_more'),
        ('management', '0030_organization_feature_face_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('email_type', models.CharField(choices=[('welcome', 'Welcome / Login Credentials'), ('leave_submitted', 'Leave Submitted'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('leave_cancelled', 'Leave Cancelled'), ('payslip', 'Payslip Generated'), ('bill', 'Student Fee Bill'), ('payment_receipt', 'Payment Receipt'), ('result', 'Exam Result Published'), ('resignation', 'Resignation Status'), ('complaint', 'Complaint Update'), ('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('task_approval', 'Task Approval'), ('password_reset', 'Password Reset'), ('attendance_summary', 'Attendance Summary'), ('other', 'Other')], default='other', max_length=30)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('related_object_type', models.CharField(blank=True, help_text="e.g. 'PaySlip', 'Bill', 'LeaveReport'", max_length=50)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='management.organization')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient_email', 'email_type', 'related_object_id'], name='handle_emai_recipie_6a3daa_idx'), models.Index(fields=['status'], name='handle_emai_status_dbd4ca_idx')],
            },
        ),
    ]
