# Generated by Django 5.2.16 on 2026-07-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0052_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('welcome', 'Welcome / Login Credentials'), ('leave_submitted', 'Leave Submitted'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('leave_cancelled', 'Leave Cancelled'), ('payslip', 'Payslip Generated'), ('bill', 'Student Fee Bill'), ('payment_receipt', 'Payment Receipt'), ('result', 'Exam Result Published'), ('resignation', 'Resignation Status'), ('complaint', 'Complaint Update'), ('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('task_overdue', 'Task Overdue'), ('task_approval', 'Task Approval'), ('password_reset', 'Password Reset'), ('attendance_summary', 'Attendance Summary'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
