# Generated by Django 5.2.16 on 2026-07-25 14:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0053_alter_emaillog_email_type'),
        ('management', '0031_organization_feature_notices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notice_attachments/')),
                ('audience', models.CharField(choices=[('org', 'Entire Organization'), ('branch', 'Specific Branch'), ('department', 'Specific Department / Class'), ('section', 'Specific Section'), ('course', 'Specific Course'), ('shift', 'Specific Shift'), ('member', 'Individual Employee / Student'), ('staff_only', 'All Staff / Employees'), ('students_only', 'All Students')], default='org', max_length=20)),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('send_email', models.BooleanField(default=False, help_text='Email this notice to its recipients when published.')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='handle.branch')),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='handle.classification')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='handle.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notices', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='management.organization')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='handle.section')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='handle.shift')),
                ('target_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_notices', to='handle.member')),
            ],
            options={
                'ordering': ('-publish_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='NoticeRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_reads', to='handle.member')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='handle.notice')),
            ],
            options={
                'ordering': ('-read_at',),
            },
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['org', 'publish_at'], name='handle_noti_org_id_af21f1_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['org', 'audience'], name='handle_noti_org_id_47a26b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='noticeread',
            unique_together={('notice', 'member')},
        ),
    ]
