# Generated by Django 5.2.16 on 2026-07-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0054_notice_noticeread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpermission',
            name='can_manage_notices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffpermission',
            name='can_view_notices',
            field=models.BooleanField(default=True),
        ),
    ]
