# Generated by Django 5.2.16 on 2026-07-26 15:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0056_alter_emaillog_email_type'),
        ('management', '0031_organization_feature_notices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfeature',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual price in Rs. Leave blank to use the standard paid-feature price.', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_code', models.CharField(help_text='Internal accession number / book code.', max_length=50)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN')),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('subject', models.CharField(blank=True, max_length=150, null=True)),
                ('edition', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Total copies owned.')),
                ('available_quantity', models.PositiveIntegerField(default=1, help_text='Copies currently on the shelf (not issued).')),
                ('lost_quantity', models.PositiveIntegerField(default=0)),
                ('damaged_quantity', models.PositiveIntegerField(default=0)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='library_covers/')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_books', to='handle.branch')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_books', to='management.organization')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='BookIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('fine', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('fine_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('late_days', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('lost', 'Lost')], default='issued', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='handle.book')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_issues', to='handle.branch')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_issued', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_issues', to='handle.member')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_issues', to='management.organization')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_returned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-issue_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LibraryAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_authors', to='management.organization')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('org', 'name')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='handle.libraryauthor'),
        ),
        migrations.CreateModel(
            name='LibraryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_categories', to='management.organization')),
            ],
            options={
                'verbose_name_plural': 'Library Categories',
                'ordering': ('name',),
                'unique_together': {('org', 'name')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='handle.librarycategory'),
        ),
        migrations.CreateModel(
            name='LibraryPublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_publishers', to='management.organization')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('org', 'name')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='handle.librarypublisher'),
        ),
        migrations.CreateModel(
            name='LibraryRack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_racks', to='handle.branch')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_racks', to='management.organization')),
            ],
            options={
                'ordering': ('code',),
                'unique_together': {('org', 'code')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='handle.libraryrack'),
        ),
        migrations.CreateModel(
            name='LibrarySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_period_days', models.PositiveIntegerField(default=14, help_text='Default days a book may be held before it is due.')),
                ('fine_per_day', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Fine charged per day overdue.', max_digits=8)),
                ('max_books_per_member', models.PositiveIntegerField(default=3, help_text='Maximum books a member may hold at once.')),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library_settings', to='management.organization')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryShelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_shelves', to='management.organization')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='handle.libraryrack')),
            ],
            options={
                'ordering': ('code',),
                'unique_together': {('rack', 'code')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='handle.libraryshelf'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('org', 'book_code')},
        ),
    ]
