# Generated by Django 5.2.16 on 2026-07-27 15:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0064_purchase_journalentry_purchase_purchaseitem_sale_and_more'),
        ('management', '0031_organization_feature_notices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advancesalary',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='handle.journalentry'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='handle.journalentry'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='journal_entry',
            field=models.ForeignKey(blank=True, help_text='Payroll accrual entry (Dr Salary Expense / Cr Salary Payable), posted when finalized.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='handle.journalentry'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='payment_journal_entry',
            field=models.ForeignKey(blank=True, help_text='Payroll payment entry (Dr Salary Payable / Cr Cash-Bank), posted when marked paid.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='handle.journalentry'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='handle.journalentry'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, default='Nepal', max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='supplier',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='municipality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='supplier',
            name='pan_vat_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='PAN/VAT Number'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='e.g. Net 30', max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='AssetPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, help_text='e.g. Furniture, Equipment, Vehicle', max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_date', models.DateField(default=django.utils.timezone.localdate)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('card', 'Card'), ('online', 'Online'), ('other', 'Other')], default='cash', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_purchases', to='handle.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_purchases_created', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='handle.journalentry')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_purchases', to='management.organization')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_purchases', to='handle.supplier')),
            ],
            options={
                'ordering': ('-purchase_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_returns', to='handle.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_returns_created', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='handle.journalentry')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_returns', to='management.organization')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='handle.purchase')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='handle.supplier')),
            ],
            options={
                'ordering': ('-return_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('purchase_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='handle.purchaseitem')),
                ('return_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='handle.purchasereturn')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_return_items', to='handle.stockitem')),
            ],
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('card', 'Card'), ('online', 'Online'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_payments', to='handle.branch')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_payments', to='handle.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_payments_created', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='handle.journalentry')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_payments', to='management.organization')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='handle.sale')),
            ],
            options={
                'ordering': ('-payment_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_returns', to='handle.branch')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_returns', to='handle.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_returns_created', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='handle.journalentry')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_returns', to='management.organization')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='handle.sale')),
            ],
            options={
                'ordering': ('-return_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('return_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='handle.salesreturn')),
                ('sale_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='handle.saleitem')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_return_items', to='handle.stockitem')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('doc_type', models.CharField(blank=True, default='other', max_length=50)),
                ('file', models.FileField(upload_to='supplier_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_documents', to='management.organization')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='handle.supplier')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('card', 'Card'), ('online', 'Online'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments', to='handle.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments_created', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='handle.journalentry')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payments', to='management.organization')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='handle.supplier')),
            ],
            options={
                'ordering': ('-payment_date', '-id'),
            },
        ),
    ]
