# Generated by Django 5.2.16 on 2026-07-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0067_client_priority_customer_bill_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(
                blank=True,
                help_text='Parent course/program, for example BSc Computing or Class 9.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='subjects',
                to='handle.course',
            ),
        ),
    ]
