# Generated by Django 4.2.5 on 2026-07-28 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


ACADEMIC_ATTENDANCE_PERMISSIONS = [
    ('can_manage_subject_assignments', 'Manage Subject Teacher Assignments', 'fa-chalkboard-user'),
    ('can_mark_subject_attendance', 'Mark Assigned Subject Attendance', 'fa-user-check'),
    ('can_view_subject_attendance_reports', 'View Subject Attendance Reports', 'fa-chart-column'),
]


def backfill_academic_hierarchy(apps, schema_editor):
    AcademicYear = apps.get_model('handle', 'AcademicYear')
    DynamicFeature = apps.get_model('handle', 'DynamicFeature')
    DynamicPermission = apps.get_model('handle', 'DynamicPermission')
    Enrollment = apps.get_model('handle', 'StudentCourseEnrollment')
    Member = apps.get_model('handle', 'member')
    RoutinePeriod = apps.get_model('handle', 'RoutinePeriod')
    SubjectTeacherAssignment = apps.get_model('handle', 'SubjectTeacherAssignment')
    TeachingLog = apps.get_model('handle', 'TeachingLog')

    current_year_by_org = {
        year.org_id: year.pk
        for year in AcademicYear.objects.filter(is_current=True, status='active').order_by('org_id', '-start_date', '-pk')
    }

    for assignment in SubjectTeacherAssignment.objects.select_related(
        'subject__course', 'subject__classification'
    ).iterator():
        subject = assignment.subject
        assignment.org_id = subject.org_id
        assignment.course_id = subject.course_id
        assignment.classification_id = subject.classification_id
        assignment.section_id = subject.section_id
        assignment.branch_id = (
            subject.course.branch_id if subject.course_id else subject.classification.branch_id
        )
        assignment.academic_year_id = current_year_by_org.get(subject.org_id)
        assignment.save(update_fields=[
            'org', 'branch', 'academic_year', 'course', 'classification', 'section',
        ])

    for period in RoutinePeriod.objects.iterator():
        period.teacher_assignment = SubjectTeacherAssignment.objects.filter(
            subject_id=period.subject_id,
            teacher_id=period.teacher_id,
        ).order_by('-is_primary', '-assigned_at').first()
        period.save(update_fields=['teacher_assignment'])

    for log in TeachingLog.objects.select_related(
        'subject__course', 'subject__classification'
    ).iterator():
        subject = log.subject
        log.course_id = subject.course_id
        log.branch_id = (
            log.branch_id
            or (subject.course.branch_id if subject.course_id else subject.classification.branch_id)
        )
        log.academic_year_id = current_year_by_org.get(log.org_id)
        log.created_by_id = log.teacher_id
        log.submitted_by_id = log.teacher_id
        log.submitted_at = log.created_at
        if log.status == 'approved':
            log.approved_by_id = log.reviewed_by_id
            log.approved_at = log.reviewed_at
        log.teacher_assignment = SubjectTeacherAssignment.objects.filter(
            subject_id=log.subject_id,
            teacher_id=log.teacher_id,
        ).order_by('-is_primary', '-assigned_at').first()
        log.save(update_fields=[
            'branch', 'academic_year', 'course', 'teacher_assignment',
            'created_by', 'submitted_by', 'submitted_at', 'approved_by', 'approved_at',
        ])

    # Only copy a current placement when the member's existing course,
    # classification and section already form a valid hierarchy. Ambiguous
    # legacy data is intentionally left for an administrator to map.
    today = django.utils.timezone.localdate()
    for student in Member.objects.exclude(org_id=None).exclude(
        classification_id=None
    ).prefetch_related('courses').iterator(chunk_size=200):
        for course in student.courses.all():
            if course.org_id != student.org_id:
                continue
            if not course.classifications.filter(pk=student.classification_id).exists():
                continue
            if student.section_id:
                if student.section.classification_id != student.classification_id:
                    continue
                if course.sections.exists() and not course.sections.filter(pk=student.section_id).exists():
                    continue
            Enrollment.objects.get_or_create(
                org_id=student.org_id,
                student_id=student.pk,
                course_id=course.pk,
                classification_id=student.classification_id,
                section_id=student.section_id,
                academic_year_id=current_year_by_org.get(student.org_id),
                start_date=student.admission_date or today,
                defaults={
                    'branch_id': student.branch_id or course.branch_id,
                    'status': 'active',
                    'notes': 'Backfilled from current member academic placement.',
                },
            )

    feature = DynamicFeature.objects.filter(key='academic_management').first()
    if feature:
        for flag, label, icon in ACADEMIC_ATTENDANCE_PERMISSIONS:
            DynamicPermission.objects.get_or_create(
                flag=flag,
                defaults={'label': label, 'icon': icon, 'feature': feature},
            )


def reverse_academic_hierarchy_backfill(apps, schema_editor):
    DynamicPermission = apps.get_model('handle', 'DynamicPermission')
    DynamicPermission.objects.filter(
        flag__in=[item[0] for item in ACADEMIC_ATTENDANCE_PERMISSIONS]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_organization_feature_notices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('handle', '0068_subject_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('transferred', 'Transferred'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-start_date', 'student__name'),
            },
        ),
        migrations.AlterModelOptions(
            name='subjectteacherassignment',
            options={'ordering': ('course__name', 'classification__name', 'section__name', 'subject__name')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectteacherassignment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('org', 'course', 'classification', 'section', 'name')},
        ),
        migrations.AddField(
            model_name='subjectattendancerecord',
            name='marked_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subjectattendancerecord',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subjectteacherassignment',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_teacher_assignments', to='handle.academicyear'),
        ),
        migrations.AddField(
            model_name='subjectteacherassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_assignments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectteacherassignment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_teacher_assignments', to='handle.branch'),
        ),
        migrations.AddField(
            model_name='subjectteacherassignment',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_teacher_assignments', to='handle.classification'),
        ),
        migrations.AddField(
            model_name='subjectteacherassignment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_teacher_assignments', to='handle.course'),
        ),
        migrations.AddField(
            model_name='subjectteacherassignment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectteacherassignment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectteacherassignment',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher_assignments', to='management.organization'),
        ),
        migrations.AddField(
            model_name='subjectteacherassignment',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_teacher_assignments', to='handle.section'),
        ),
        migrations.AddField(
            model_name='subjectteacherassignment',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='subjectteacherassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='subjectteacherassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teachinglog',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_logs', to='handle.academicyear'),
        ),
        migrations.AddField(
            model_name='teachinglog',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachinglog',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_logs_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teachinglog',
            name='attendance_excused',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teachinglog',
            name='attendance_late',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teachinglog',
            name='attendance_leave',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teachinglog',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_logs', to='handle.course'),
        ),
        migrations.AddField(
            model_name='teachinglog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_logs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teachinglog',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachinglog',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teachinglog',
            name='routine_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_logs', to='handle.routineperiod'),
        ),
        migrations.AddField(
            model_name='teachinglog',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachinglog',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachinglog',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_logs_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teachinglog',
            name='teacher_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_logs', to='handle.subjectteacherassignment'),
        ),
        migrations.AddField(
            model_name='routineperiod',
            name='teacher_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_periods', to='handle.subjectteacherassignment'),
        ),
        migrations.AlterField(
            model_name='subjectattendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused'), ('leave', 'Leave')], default='present', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachinglog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
        migrations.AddIndex(
            model_name='subjectattendancerecord',
            index=models.Index(fields=['org', 'status'], name='handle_subj_org_id_6bd7bd_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectattendancerecord',
            index=models.Index(fields=['member', 'status'], name='handle_subj_member__2e62ae_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectteacherassignment',
            index=models.Index(fields=['org', 'academic_year', 'course', 'status'], name='handle_subj_org_id_2516cc_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectteacherassignment',
            index=models.Index(fields=['org', 'classification', 'section', 'status'], name='handle_subj_org_id_728873_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectteacherassignment',
            index=models.Index(fields=['teacher', 'status', 'start_date', 'end_date'], name='handle_subj_teacher_0f3a09_idx'),
        ),
        migrations.AddIndex(
            model_name='teachinglog',
            index=models.Index(fields=['org', 'date', 'status'], name='handle_teac_org_id_35ae08_idx'),
        ),
        migrations.AddIndex(
            model_name='teachinglog',
            index=models.Index(fields=['org', 'course', 'classification', 'section'], name='handle_teac_org_id_11ac24_idx'),
        ),
        migrations.AddIndex(
            model_name='teachinglog',
            index=models.Index(fields=['teacher', 'date', 'status'], name='handle_teac_teacher_cc1a74_idx'),
        ),
        migrations.AddIndex(
            model_name='teachinglog',
            index=models.Index(fields=['subject', 'date', 'period'], name='handle_teac_subject_6546d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='subjectteacherassignment',
            constraint=models.UniqueConstraint(fields=('subject', 'teacher', 'academic_year', 'start_date'), name='unique_subject_teacher_year_start'),
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_enrollments', to='handle.academicyear'),
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_course_enrollments', to='handle.branch'),
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='handle.classification'),
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='handle.course'),
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_course_enrollments', to='management.organization'),
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_enrollments', to='handle.section'),
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='handle.member'),
        ),
        migrations.RunPython(
            backfill_academic_hierarchy,
            reverse_academic_hierarchy_backfill,
        ),
        migrations.AddIndex(
            model_name='studentcourseenrollment',
            index=models.Index(fields=['org', 'academic_year', 'course', 'status'], name='handle_stud_org_id_c22ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcourseenrollment',
            index=models.Index(fields=['org', 'classification', 'section', 'status'], name='handle_stud_org_id_48eb7d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcourseenrollment',
            index=models.Index(fields=['student', 'status'], name='handle_stud_student_9b8779_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentcourseenrollment',
            constraint=models.UniqueConstraint(fields=('student', 'course', 'classification', 'section', 'academic_year', 'start_date'), name='unique_student_academic_enrollment_start'),
        ),
    ]
