# Generated by Django 4.2.5 on 2026-07-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0069_academic_hierarchy_attendance_workflow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subjectteacherassignment',
            name='unique_subject_teacher_year_start',
        ),
        migrations.AddConstraint(
            model_name='subjectteacherassignment',
            constraint=models.UniqueConstraint(
                fields=(
                    'subject',
                    'teacher',
                    'academic_year',
                    'section',
                    'start_date',
                ),
                name='unique_subject_teacher_year_start',
            ),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher_assignment',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assignments',
                to='handle.subjectteacherassignment',
            ),
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher_assignment',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='homeworks',
                to='handle.subjectteacherassignment',
            ),
        ),
    ]
