# Generated by Django 5.2.16 on 2026-07-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0070_teacher_scoped_student_work'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inappnotification',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('homework_assigned', 'Homework Assigned'),
                    ('assignment_assigned', 'Assignment Assigned'),
                    ('assignment_due', 'Assignment Due'),
                    ('submission_received', 'Submission Received'),
                    ('marks_published', 'Marks Published'),
                    ('course_material_added', 'New Course Material'),
                    ('teaching_log_reviewed', 'Teaching Log Reviewed'),
                    ('task_assigned', 'Task Assigned'),
                    ('task_started', 'Task Started'),
                    ('task_due_today', 'Task Due Today'),
                    ('task_overdue', 'Task Overdue'),
                    ('task_completed', 'Task Completed'),
                    ('task_not_completed', 'Task Not Completed'),
                    ('task_approved', 'Task Approved'),
                    ('task_rejected', 'Task Rejected'),
                    ('task_reassigned', 'Task Reassigned'),
                    ('task_cancelled', 'Task Cancelled'),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name='inappnotification',
            name='recipient',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='in_app_notifications',
                to='handle.member',
            ),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='action_label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='actor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='triggered_in_app_notifications',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='dedupe_key',
            field=models.CharField(
                blank=True, max_length=190, null=True, unique=True,
            ),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='priority',
            field=models.CharField(
                choices=[
                    ('low', 'Low'),
                    ('normal', 'Normal'),
                    ('high', 'High'),
                    ('urgent', 'Urgent'),
                ],
                default='normal',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='recipient_user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='direct_in_app_notifications',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name='inappnotification',
            index=models.Index(
                fields=['org', 'is_read', 'created_at'],
                name='notif_org_read_created_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='inappnotification',
            index=models.Index(
                fields=['recipient', 'is_read'],
                name='notif_member_read_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='inappnotification',
            index=models.Index(
                fields=['recipient_user', 'is_read'],
                name='notif_user_read_idx',
            ),
        ),
    ]
