# Generated by Django 5.2.16 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0071_premium_notifications'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inappnotification',
            constraint=models.CheckConstraint(
                check=(
                    models.Q(('recipient__isnull', False))
                    | models.Q(('recipient_user__isnull', False))
                ),
                name='notification_has_recipient',
            ),
        ),
    ]
