# Generated by Django 4.2.5 on 2026-07-31.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_featureprice_organization_commercial_fields'),
        ('handle', '0077_transport_and_permanent_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADMSAttendanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_hash', models.CharField(max_length=64)),
                ('device_user_id', models.CharField(blank=True, max_length=50)),
                ('event_time', models.DateTimeField(blank=True, null=True)),
                ('punch_state', models.CharField(blank=True, max_length=20)),
                ('verify_mode', models.CharField(blank=True, max_length=20)),
                ('work_code', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('stored', 'Stored'), ('unmatched', 'Unmatched member'), ('ambiguous', 'Ambiguous member PIN'), ('inactive', 'Inactive member'), ('invalid', 'Invalid row')], default='stored', max_length=12)),
                ('raw_payload', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-received_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='device',
            name='connection_mode',
            field=models.CharField(choices=[('pull', 'Local SDK / Puller'), ('adms', 'ADMS Cloud Push')], default='pull', max_length=10),
        ),
        migrations.AddField(
            model_name='device',
            name='last_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_push_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='push_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Device serial number (SN) shown in Device Information.', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='port_no',
            field=models.IntegerField(default=4370),
        ),
        migrations.AddField(
            model_name='admsattendanceevent',
            name='attendance_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adms_events', to='handle.attendancerecord'),
        ),
        migrations.AddField(
            model_name='admsattendanceevent',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adms_events', to='handle.device'),
        ),
        migrations.AddField(
            model_name='admsattendanceevent',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adms_events', to='handle.member'),
        ),
        migrations.AddField(
            model_name='admsattendanceevent',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adms_events', to='management.organization'),
        ),
        migrations.AddIndex(
            model_name='admsattendanceevent',
            index=models.Index(fields=['org', 'received_at'], name='handle_adms_org_id_b9fedb_idx'),
        ),
        migrations.AddIndex(
            model_name='admsattendanceevent',
            index=models.Index(fields=['device_user_id', 'event_time'], name='handle_adms_device__0b6a32_idx'),
        ),
        migrations.AddConstraint(
            model_name='admsattendanceevent',
            constraint=models.UniqueConstraint(fields=('device', 'event_hash'), name='unique_adms_event_per_device'),
        ),
    ]
