# Generated by Django 4.2.5 on 2026-07-31 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_featureprice_organization_commercial_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('handle', '0078_admsattendanceevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='profile_updated', max_length=80)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-changed_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='MemberWeekdayShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('member__name', 'weekday'),
            },
        ),
        migrations.RenameIndex(
            model_name='livetrackingsession',
            new_name='handle_live_org_id_3489d7_idx',
            old_name='handle_live_org_id_a959bf_idx',
        ),
        migrations.AddField(
            model_name='memberweekdayshift',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekday_shifts', to='handle.member'),
        ),
        migrations.AddField(
            model_name='memberweekdayshift',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_weekday_shifts', to='management.organization'),
        ),
        migrations.AddField(
            model_name='memberweekdayshift',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekday_assignments', to='handle.shift'),
        ),
        migrations.AddField(
            model_name='memberhistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memberhistory',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to='handle.member'),
        ),
        migrations.AddField(
            model_name='memberhistory',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_history', to='management.organization'),
        ),
        migrations.AddIndex(
            model_name='memberweekdayshift',
            index=models.Index(fields=['org', 'weekday'], name='handle_memb_org_id_21336d_idx'),
        ),
        migrations.AddConstraint(
            model_name='memberweekdayshift',
            constraint=models.UniqueConstraint(fields=('member', 'weekday'), name='unique_member_shift_per_weekday'),
        ),
        migrations.AddConstraint(
            model_name='memberweekdayshift',
            constraint=models.CheckConstraint(check=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='member_weekday_shift_valid_day'),
        ),
        migrations.AddIndex(
            model_name='memberhistory',
            index=models.Index(fields=['org', 'member', 'changed_at'], name='handle_memb_org_id_e42e7e_idx'),
        ),
    ]
