# Generated by Django 4.2.5 on 2026-07-31 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_occasion_unique_occasion_name_date_per_org'),
        ('handle', '0079_memberhistory_memberweekdayshift_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStudentTripStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('picked_up', 'Picked Up'), ('dropped_off', 'Dropped Off'), ('skipped', 'Skipped')], default='waiting', max_length=20)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('dropped_off_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_statuses', to='handle.studentbusassignment')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_trip_statuses', to='handle.schoolbus')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_bus_student_statuses', to='handle.member')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_student_trip_statuses', to='management.organization')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_statuses', to='handle.bustrackingsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_trip_statuses', to='handle.member')),
            ],
            options={
                'ordering': ('assignment__student__name',),
                'indexes': [models.Index(fields=['org', 'session', 'status'], name='handle_buss_org_id_cdd2f5_idx'), models.Index(fields=['student', 'updated_at'], name='handle_buss_student_59283c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='busstudenttripstatus',
            constraint=models.UniqueConstraint(fields=('session', 'assignment'), name='unique_student_state_per_bus_trip'),
        ),
    ]
