# Generated by Django 4.2.5 on 2026-07-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0080_bus_student_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfollowup',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AddIndex(
            model_name='clientfollowup',
            index=models.Index(fields=['org', 'priority', 'next_follow_up_date'], name='handle_clie_org_id_9a479f_idx'),
        ),
    ]
