# Generated by Django 5.2.16 on 2026-07-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0081_client_followup_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='previous_status',
            field=models.CharField(blank=True, help_text='Status held right before being dumped — restored on rejoin.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('passed_out', 'Passed Out'), ('dropped', 'Dropped'), ('transferred', 'Transferred'), ('suspended', 'Suspended'), ('restricted', 'Restricted'), ('resigned', 'Resigned'), ('intern', 'Intern'), ('probation', 'Probation'), ('dumped', 'Dumped')], default='active', max_length=30),
        ),
    ]
