# Generated by Django 5.2.16 on 2026-08-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0082_member_previous_status_alter_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='archive_file',
            field=models.CharField(blank=True, help_text="Relative media path to the JSON archive of this member's records while dumped.", max_length=255, null=True),
        ),
    ]
