# Generated by Django 4.2.5 on 2026-08-01 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def disable_legacy_optional_id_fields(apps, schema_editor):
    IDCardTemplate = apps.get_model('handle', 'IDCardTemplate')
    IDCardTemplate.objects.update(
        show_blood_group=False,
        show_signature=False,
        show_valid_until=False,
    )


def noop_reverse(apps, schema_editor):
    # The old values cannot be reconstructed reliably; the columns remain in
    # place, so reversing the schema is still safe.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0036_packagerequest_alter_contactus_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('handle', '0083_member_archive_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcardtemplate',
            name='base_font_size',
            field=models.PositiveSmallIntegerField(default=10, help_text='Detail text size in pixels.'),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='card_title',
            field=models.CharField(blank=True, default='', help_text='Optional heading such as STUDENT ID CARD.', max_length=80),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='font_family',
            field=models.CharField(choices=[('inter', 'Inter / Arial'), ('poppins', 'Poppins / Arial'), ('roboto', 'Roboto / Arial'), ('montserrat', 'Montserrat / Arial'), ('georgia', 'Georgia / Serif'), ('times', 'Times New Roman / Serif')], default='inter', max_length=20),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='footer_text',
            field=models.CharField(blank=True, default='', help_text='Optional text printed on the back of the card.', max_length=180),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='line_height',
            field=models.DecimalField(decimal_places=2, default=1.35, max_digits=3),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='name_font_size',
            field=models.PositiveSmallIntegerField(default=14, help_text='Member name size in pixels.'),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='org_font_size',
            field=models.PositiveSmallIntegerField(default=13, help_text='Organization name size in pixels.'),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='text_color',
            field=models.CharField(default='#111827', help_text='Main card text color.', max_length=7),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='show_blood_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='show_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='show_valid_until',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(disable_legacy_optional_id_fields, noop_reverse),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('certificate_type', models.CharField(choices=[('completion', 'Course Completion'), ('achievement', 'Achievement'), ('participation', 'Participation'), ('training', 'Training'), ('experience', 'Experience'), ('appreciation', 'Appreciation'), ('character', 'Character / Conduct'), ('membership', 'Membership'), ('custom', 'Custom Certificate')], default='completion', max_length=30)),
                ('orientation', models.CharField(choices=[('landscape', 'A4 Landscape'), ('portrait', 'A4 Portrait')], default='landscape', max_length=12)),
                ('title', models.CharField(default='Certificate of Completion', max_length=160)),
                ('subtitle', models.CharField(blank=True, default='This certificate is proudly presented to', max_length=200)),
                ('body_html', models.TextField(default='<p>For successfully completing the prescribed programme at <strong>[[organization]]</strong>.</p>', help_text='Rich text. Use the supported [[tokens]] for member data.')),
                ('footer_text', models.CharField(blank=True, default='', max_length=240)),
                ('serial_prefix', models.CharField(blank=True, default='CERT', max_length=20)),
                ('primary_color', models.CharField(default='#172554', max_length=7)),
                ('secondary_color', models.CharField(default='#c59d3f', max_length=7)),
                ('text_color', models.CharField(default='#1f2937', max_length=7)),
                ('border_style', models.CharField(choices=[('classic', 'Classic Double Border'), ('modern', 'Modern Corner Border'), ('minimal', 'Minimal Single Border'), ('none', 'No Border')], default='classic', max_length=20)),
                ('font_family', models.CharField(choices=[('inter', 'Inter / Arial'), ('poppins', 'Poppins / Arial'), ('roboto', 'Roboto / Arial'), ('montserrat', 'Montserrat / Arial'), ('georgia', 'Georgia / Serif'), ('times', 'Times New Roman / Serif')], default='georgia', max_length=20)),
                ('title_font_size', models.PositiveSmallIntegerField(default=38)),
                ('recipient_font_size', models.PositiveSmallIntegerField(default=34)),
                ('body_font_size', models.PositiveSmallIntegerField(default=17)),
                ('line_height', models.DecimalField(decimal_places=2, default=1.6, max_digits=3)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='certificate_backgrounds')),
                ('letterhead_image', models.ImageField(blank=True, null=True, upload_to='certificate_letterheads')),
                ('show_logo', models.BooleanField(default=True)),
                ('show_issue_date', models.BooleanField(default=True)),
                ('show_certificate_number', models.BooleanField(default=True)),
                ('signature_one_name', models.CharField(blank=True, default='', max_length=100)),
                ('signature_one_title', models.CharField(blank=True, default='Authorized Signature', max_length=100)),
                ('signature_one_image', models.ImageField(blank=True, null=True, upload_to='certificate_signatures')),
                ('signature_two_name', models.CharField(blank=True, default='', max_length=100)),
                ('signature_two_title', models.CharField(blank=True, default='', max_length=100)),
                ('signature_two_image', models.ImageField(blank=True, null=True, upload_to='certificate_signatures')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_certificate_templates', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='management.organization')),
            ],
            options={
                'ordering': ('-is_default', 'name'),
                'indexes': [models.Index(fields=['org', 'is_active'], name='handle_cert_org_id_a1c174_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='certificatetemplate',
            constraint=models.UniqueConstraint(fields=('org', 'name'), name='unique_certificate_template_name_per_org'),
        ),
    ]
