# Generated by Django 5.2.16 on 2026-08-06 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0084_document_designer'),
        ('management', '0037_seed_homepage_faqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberShiftOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('member__name', 'date'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='memberweekdayshift',
            name='unique_member_shift_per_weekday',
        ),
        migrations.AddConstraint(
            model_name='memberweekdayshift',
            constraint=models.UniqueConstraint(fields=('member', 'weekday', 'shift'), name='unique_member_weekday_shift_row'),
        ),
        migrations.AddField(
            model_name='membershiftoverride',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_overrides', to='handle.member'),
        ),
        migrations.AddField(
            model_name='membershiftoverride',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_shift_overrides', to='management.organization'),
        ),
        migrations.AddField(
            model_name='membershiftoverride',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='date_overrides', to='handle.shift'),
        ),
        migrations.AddIndex(
            model_name='membershiftoverride',
            index=models.Index(fields=['org', 'date'], name='handle_memb_org_id_6d4b95_idx'),
        ),
        migrations.AddConstraint(
            model_name='membershiftoverride',
            constraint=models.UniqueConstraint(fields=('member', 'date', 'shift'), name='unique_member_date_shift_row'),
        ),
    ]
