# Generated by Django 5.2.16 on 2026-08-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0085_member_shift_overrides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldvisit',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldvisit',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
