# Generated by Django 5.2.16 on 2026-08-06 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0086_field_visit_optional_coordinates'),
        ('management', '0038_organization_default_shift_and_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfollowup',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientfollowup',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_follow_ups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientfollowup',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10),
        ),
        migrations.AddIndex(
            model_name='clientfollowup',
            index=models.Index(fields=['org', 'status'], name='handle_clie_org_id_a1056b_idx'),
        ),
    ]
