# Generated by Django 5.2.16 on 2026-08-16 15:53

from django.db import migrations, models


def backfill_branches_m2m(apps, schema_editor):
    """Copy each Classification's existing single `branch` FK into the new
    `branches` M2M, so existing single-branch scoping keeps behaving exactly
    as before. Classifications with no branch (org-wide) are left with an
    empty M2M, which is the new model's own meaning of "all branches"."""
    Classification = apps.get_model('handle', 'Classification')
    for classification in Classification.objects.exclude(branch__isnull=True):
        classification.branches.add(classification.branch_id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0087_client_followup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='branches',
            field=models.ManyToManyField(blank=True, help_text='Branches that can use this classification. Leave empty to make it available to all branches.', related_name='available_classifications', to='handle.branch'),
        ),
        migrations.RunPython(backfill_branches_m2m, noop_reverse),
    ]
