# Generated by Django 5.2.16 on 2026-08-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0089_emaillog_broadcast_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='default_shift_end_time',
            field=models.TimeField(blank=True, help_text='Suggested check-out time for new members at this branch. Leave blank to use the organization default.', null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='default_shift_start_time',
            field=models.TimeField(blank=True, help_text='Suggested check-in time for new members at this branch. Leave blank to use the organization default.', null=True),
        ),
        migrations.AddField(
            model_name='classification',
            name='default_shift_end_time',
            field=models.TimeField(blank=True, help_text='Suggested check-out time for new members in this classification. Leave blank to use the branch/organization default.', null=True),
        ),
        migrations.AddField(
            model_name='classification',
            name='default_shift_start_time',
            field=models.TimeField(blank=True, help_text='Suggested check-in time for new members in this classification. Leave blank to use the branch/organization default.', null=True),
        ),
    ]
