# Generated by Django 5.2.16 on 2026-08-16 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0090_branch_classification_default_shift'),
        ('management', '0038_organization_default_shift_and_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, db_index=True, help_text='Leave blank for an open-ended (ongoing) change.', null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Cancelled changes are kept (not deleted) so roster history stays intact.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_shift_assignments', to='handle.member')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_shift_assignments', to='management.organization')),
                ('shift', models.ForeignKey(blank=True, help_text='Leave blank to mark the member off-duty for this whole date range.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temporary_assignments', to='handle.shift')),
            ],
            options={
                'ordering': ('-start_date',),
                'indexes': [models.Index(fields=['org', 'member', 'is_active'], name='handle_temp_org_id_2615b4_idx')],
            },
        ),
    ]
