# Generated by Django 5.2.16 on 2026-08-17 03:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0091_temporary_shift_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='attachment',
            field=models.FileField(blank=True, help_text='Scanned bill / invoice document from the supplier.', null=True, upload_to='purchase_bills/'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='purchase',
            name='due_date',
            field=models.DateField(blank=True, help_text='When payment to the supplier is due for this specific bill.', null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='purchase',
            field=models.ForeignKey(blank=True, help_text="Optionally tie this payment to one specific bill, instead of just the supplier's running balance.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_payments', to='handle.purchase'),
        ),
    ]
