# Generated by Django 5.2.16 on 2026-08-18 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0094_dailynote'),
        ('management', '0038_organization_default_shift_and_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgPrintDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_key', models.CharField(max_length=50)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_defaults', to='management.organization')),
            ],
            options={
                'unique_together': {('org', 'report_key')},
            },
        ),
    ]
