# Generated by Django 5.2.16 on 2026-08-18 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0095_orgprintdefault'),
        ('management', '0039_organization_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='Pre-selected when building a new roster entry.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_types', to='management.organization')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('org', 'name')},
            },
        ),
        migrations.AddField(
            model_name='temporaryshiftassignment',
            name='duty_type',
            field=models.ForeignKey(blank=True, help_text="What kind of duty this is (e.g. Regular, On-Call) - independent of the shift's time window.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporary_assignments', to='handle.dutytype'),
        ),
    ]
