/* Mero Attendance service worker — generated by school/pwa.py.
 *
 * Caching rules (see school/pwa.py for the full rationale):
 *   navigation/HTML : network-first, NEVER cached  <- multi-tenant safety
 *   static assets   : stale-while-revalidate
 *   non-GET         : never intercepted
 */
const VERSION       = "{{ cache_version }}";
const STATIC_CACHE  = "ma-static-" + VERSION;
const OFFLINE_URL   = "{{ offline_url }}";
const PRECACHE      = [
{% for u in precache_urls %}  "{{ u }}",
{% endfor %}  OFFLINE_URL
];

// Never let the worker touch these: media is user-uploaded and may be private,
// and auth/admin flows must always hit the network.
const BYPASS = [/^\/media\//, /^\/admin\//, /^\/logout/, /^\/api\//];

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(STATIC_CACHE);
    // addAll() is atomic — one 404 would abort the whole install, so add
    // individually and tolerate misses.
    await Promise.all(PRECACHE.map((u) =>
      cache.add(new Request(u, { cache: "reload" })).catch(() => null)
    ));
    self.skipWaiting();
  })());
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(
      keys.filter((k) => k.startsWith("ma-static-") && k !== STATIC_CACHE)
          .map((k) => caches.delete(k))
    );
    if (self.registration.navigationPreload) {
      await self.registration.navigationPreload.enable();
    }
    await self.clients.claim();
  })());
});

function isStaticAsset(url) {
  return url.pathname.startsWith("/static/");
}

self.addEventListener("fetch", (event) => {
  const req = event.request;
  const url = new URL(req.url);

  // Only ever handle same-origin GETs.
  if (req.method !== "GET" || url.origin !== self.location.origin) return;
  if (BYPASS.some((re) => re.test(url.pathname))) return;

  // ── Navigations: network-first, response never stored ───────────────────
  if (req.mode === "navigate") {
    event.respondWith((async () => {
      try {
        const preloaded = await event.preloadResponse;
        if (preloaded) return preloaded;
        return await fetch(req);
      } catch (err) {
        // Offline: we deliberately have no cached page to fall back to,
        // because it could belong to a different signed-in user.
        const cache = await caches.open(STATIC_CACHE);
        return (await cache.match(OFFLINE_URL)) ||
               new Response("You are offline.", {
                 status: 503, headers: { "Content-Type": "text/plain" }
               });
      }
    })());
    return;
  }

  // ── Static assets: stale-while-revalidate ──────────────────────────────
  if (isStaticAsset(url)) {
    event.respondWith((async () => {
      const cache = await caches.open(STATIC_CACHE);
      const cached = await cache.match(req);
      const network = fetch(req).then((res) => {
        if (res && res.status === 200 && res.type === "basic") {
          cache.put(req, res.clone());
        }
        return res;
      }).catch(() => null);
      return cached || (await network) ||
             new Response("", { status: 504 });
    })());
  }
  // Everything else (HTMX partials, form posts, etc.) falls through to the
  // network untouched — those responses carry tenant data.
});

// Lets the page tell a waiting worker to take over immediately.
self.addEventListener("message", (event) => {
  if (event.data === "SKIP_WAITING") self.skipWaiting();
});
